---
- name: Install Apache and Upload my Web Page
  hosts: *{{ MYHOSTS }}*
  became: yes


  vars:
    source_folder: ./MyWebSite
    destin_folder: /var/www/html

  tasks:
  - name: Check and Print LINUX version
    debug: var=ansible_os_family

  - block:  #  =========Block for RedHat=========

      - name: Install Apache Web Server for RadHat
        yum: name=httpd state=latest

      - name: Start WebServer and make it enable on boot for RadHat
        service: name=httpd state=started enabled=yes
      
    when: ansible_os_family == 'RadHat'


  - block:  #  =========Block for Debian=========
      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Start WebServer and make it enable on boot for Debian
        service: name=apache2 state=started enabled=yes
   
    when: ansible_os_family == 'Debian'


  - name: Copy folder MyHomePage to Servers
# Exl.1
#    copy: src={{  source_folder }}/{{ item }} dest={{ destin_folder }} mode=0555 
#    loop:
#       - 'index.html'
#       - 'bahamas.png'
#       - 'bulgaria.png'
#       - 'jordan.png'
#       - 'newzeland.png'
# Exl.2
    copy: src={{ item }} dest={{ destin_folder }} mode=0555
    with_fileglob: '{{ source_folder }}/*.*'
    notify: 
       - Restart Apache RedHat
       - Restart Apache Debian


  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == 'RadHat'

  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == 'Debian'
